name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Restore dependencies
        run: dotnet restore JadeDSL.sln

      - name: 🧱 Build solution
        run: dotnet build JadeDSL.sln --configuration Release

      - name: ✅ Run tests
        run: dotnet test JadeDSL.sln --configuration Release --verbosity normal
